### ISSUE TITLE
Incorrect message when accessing non-existent users

### ISSUE THREAD

**Issue by impathrion** [edward-dunton/Metis#11]
labels: bug
assignees: Keartland

---

**Describe the bug**
When signed in and trying to access https://metis.ga/profile/HarryM you receive the "need to be signed in to view HarryM" (screen 1) and it behaves as if you were signed out (even when you go to the homepage (screen 2). However, when you go to your userpage without signing in again the session is still active and you are logged in (screen 3) and when you navigate to the homepage from there it behaves normally (screen 4)

**To Reproduce**
1. Sign in
2. Enter https://metis.ga/profile/HarryM in the browser [for non-existent users or for Harry it works just fine]
3. Click on the homepage button
4. Enter  https://metis.ga/profile/[your_username] in the browser
5. Click on the homepage button

**Error Messages**
No errors

**Screenshots**
Screen 1
![obraz](https://user-images.githubusercontent.com/32000052/110971771-2fa81180-8353-11eb-839e-b5e69e6dc640.png)

Screen 2
![obraz](https://user-images.githubusercontent.com/32000052/110971895-55351b00-8353-11eb-8e3b-281f25871200.png)

Screen 3
![obraz](https://user-images.githubusercontent.com/32000052/110972046-785fca80-8353-11eb-9f00-6f6f2e53f0e3.png)

Screen 4
![obraz](https://user-images.githubusercontent.com/32000052/110972159-988f8980-8353-11eb-81c2-ba540110fcb1.png)

**Additional context**

**Comment by Keartland** [comment]
should be fixed in next prod!
