### ISSUE TITLE
Modules do not appear in the publish dropdown until page is refreshed

### ISSUE THREAD

**Issue by eddy-dunton** [edward-dunton/Metis#8]
**Describe the bug**
Modules do not appear in the publish dropdown until page is refreshed

**To Reproduce**
1. Go to profile
2. Join Unit
3. Press Publish
4. Newly joined unit does not appear from unit dropdown until page is refreshed

**Error Messages**
None

**Additional context**
None

**Comment by Keartland** [comment]
Can you check current site and see if this still exists, cant recreate.
