### ISSUE TITLE
Welcome page sign in / create account do nothing

### ISSUE THREAD

**Issue by edward-dunton** [edward-dunton/Metis#9]
**Describe the bug**
As title
When signing in it appears it doesn't send the username  / email
And the create account button seems to be linked up to nothing

**To Reproduce**
1. Go to metis.ga
2. Enter valid credientials (in either login or create account)
3. Press button

**Error Messages**
Login: isUser returns 400: No username or email field
Create Account: No error message appears, even after pressing the button multiple times (seems no request is sent)

**Screenshots**
![image](https://user-images.githubusercontent.com/42977035/110658992-10c24780-81ba-11eb-9e34-3f6c2498e3ec.png)

**Additional context**

**Comment by Keartland** [comment]
fixed in newest prod!
